"""create registered_business_types table

Revision ID: 02acc51586c9
Revises: 29ec9ac716df
Create Date: 2024-07-08 19:55:13.153052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02acc51586c9'
down_revision = '29ec9ac716df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regsitered_business_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regsitered_business_types')
    # ### end Alembic commands ###
