"""create prefecture check in table

Revision ID: 04bb6a2a826b
Revises: 3fa41ab090e8
Create Date: 2024-07-18 10:22:50.827084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bb6a2a826b'
down_revision = '3fa41ab090e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefecture_checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visited', sa.Boolean(), nullable=True),
    sa.Column('prefecture_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_prefecture_checkin_admin_id_admins')),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_prefecture_checkin_citizen_id_citizens')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_prefecture_checkin_prefecture_id_prefectures')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_prefecture_checkin_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefecture_checkin')
    # ### end Alembic commands ###
