"""create check in for business table

Revision ID: 0e8ac831d4a9
Revises: 40a5a642e895
Create Date: 2024-07-22 11:20:18.971410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8ac831d4a9'
down_revision = '40a5a642e895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visited', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_checkin_business_id_businesses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_business_checkin_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_checkin')
    # ### end Alembic commands ###
