"""updating business_reviews tabl with business_id

Revision ID: 1b627565522b
Revises: 5a3682e73949
Create Date: 2024-07-07 23:39:35.148237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b627565522b'
down_revision = '5a3682e73949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_business_reviews_business_id_businesses'), 'businesses', ['business_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_business_reviews_business_id_businesses'), type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
