"""update business reviews tables so that admin can leave a review

Revision ID: 29ec9ac716df
Revises: a10012acf89f
Create Date: 2024-07-07 23:54:34.745166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ec9ac716df'
down_revision = 'a10012acf89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_business_reviews_admin_id_admins'), 'admins', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_business_reviews_admin_id_admins'), type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
