"""create prefecture wish list model

Revision ID: 2a5c54012b42
Revises: 48a65ab65b7e
Create Date: 2024-07-18 20:00:17.746555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5c54012b42'
down_revision = '48a65ab65b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefecture_wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_list', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefecture_wishlist')
    # ### end Alembic commands ###
