"""updating business wishlist

Revision ID: 313daf5b147a
Revises: 6a38f036b0b2
Create Date: 2024-07-27 19:03:11.745081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313daf5b147a'
down_revision = '6a38f036b0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_wishlist', schema=None) as batch_op:
        batch_op.drop_column('wish_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wish_list', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
