"""set up Citizen table

Revision ID: 35aa3c75d2cf
Revises: 7391325803e0
Create Date: 2024-06-30 10:00:13.941761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35aa3c75d2cf'
down_revision = '7391325803e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('home_country', sa.String(), nullable=True),
    sa.Column('current_town', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_citizens_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citizens')
    # ### end Alembic commands ###
