"""create prefecture ratings table

Revision ID: 3fa41ab090e8
Revises: 6d1a734a6023
Create Date: 2024-07-17 11:24:39.628376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa41ab090e8'
down_revision = '6d1a734a6023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefecture_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefecture_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=True),
    sa.Column('prefecture_type_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_prefecture_reviews_admin_id_admins')),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_prefecture_reviews_citizen_id_citizens')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_prefecture_reviews_prefecture_id_prefectures')),
    sa.ForeignKeyConstraint(['prefecture_type_id'], ['prefecture_reviews.id'], name=op.f('fk_prefecture_reviews_prefecture_type_id_prefecture_reviews')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_prefecture_reviews_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prefecture_review_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefecture_review_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('prefecture_id', sa.INTEGER(), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('traveler_id', sa.INTEGER(), nullable=True),
    sa.Column('citizen_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='fk_prefecture_review_types_admin_id_admins'),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name='fk_prefecture_review_types_citizen_id_citizens'),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name='fk_prefecture_review_types_prefecture_id_prefectures'),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name='fk_prefecture_review_types_traveler_id_travelers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prefecture_reviews')
    op.drop_table('prefecture_categories')
    # ### end Alembic commands ###
