"""update the citizen, admin and travelers models to include current towns and countries

Revision ID: 40a5a642e895
Revises: 4b6b323abc5d
Create Date: 2024-07-19 18:59:07.416578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a5a642e895'
down_revision = '4b6b323abc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_town', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_country', sa.String(), nullable=True))

    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_country', sa.String(), server_default='Japan', nullable=True))

    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_town', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_country', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.drop_column('current_country')
        batch_op.drop_column('current_town')

    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.drop_column('current_country')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('current_country')
        batch_op.drop_column('current_town')

    # ### end Alembic commands ###
