"""upgrade prefecture_checkin model to show only user id

Revision ID: 48a65ab65b7e
Revises: 04bb6a2a826b
Create Date: 2024-07-18 10:57:17.021543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a65ab65b7e'
down_revision = '04bb6a2a826b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_checkin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_prefecture_checkin_traveler_id_travelers', type_='foreignkey')
        batch_op.drop_constraint('fk_prefecture_checkin_admin_id_admins', type_='foreignkey')
        batch_op.drop_constraint('fk_prefecture_checkin_citizen_id_citizens', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_prefecture_checkin_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('citizen_id')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('traveler_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_checkin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traveler_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('citizen_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_prefecture_checkin_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_prefecture_checkin_citizen_id_citizens', 'citizens', ['citizen_id'], ['id'])
        batch_op.create_foreign_key('fk_prefecture_checkin_admin_id_admins', 'admins', ['admin_id'], ['id'])
        batch_op.create_foreign_key('fk_prefecture_checkin_traveler_id_travelers', 'travelers', ['traveler_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
