"""update prefecture wishlist table

Revision ID: 4b6b323abc5d
Revises: 2a5c54012b42
Create Date: 2024-07-18 20:27:17.665346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6b323abc5d'
down_revision = '2a5c54012b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefecture_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_prefecture_wishlist_prefecture_id_prefectures'), 'prefectures', ['prefecture_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_prefecture_wishlist_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_prefecture_wishlist_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_prefecture_wishlist_prefecture_id_prefectures'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('prefecture_id')

    # ### end Alembic commands ###
