"""create a business wishlist table

Revision ID: 4badc5be2f2a
Revises: 0e8ac831d4a9
Create Date: 2024-07-23 09:37:20.170533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4badc5be2f2a'
down_revision = '0e8ac831d4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_list', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_wishlist_business_id_businesses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_business_wishlist_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_wishlist')
    # ### end Alembic commands ###
