"""creating business_reviews table

Revision ID: 5a3682e73949
Revises: 793e00e2e579
Create Date: 2024-07-07 23:37:25.457190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3682e73949'
down_revision = '793e00e2e579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_rating', sa.Integer(), nullable=False),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_business_reviews_citizen_id_citizens')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_business_reviews_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_reviews')
    # ### end Alembic commands ###
