"""update business check in model

Revision ID: 6084c8a59d17
Revises: 10f75c725056
Create Date: 2024-08-11 21:33:36.581871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6084c8a59d17'
down_revision = '10f75c725056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_checkin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_checkin', schema=None) as batch_op:
        batch_op.drop_column('check_in_date')

    # ### end Alembic commands ###
