"""update businessCheckInModel

Revision ID: 6a38f036b0b2
Revises: ded26f67a338
Create Date: 2024-07-27 12:35:12.754259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a38f036b0b2'
down_revision = 'ded26f67a338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_checkin', schema=None) as batch_op:
        batch_op.drop_column('visited')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_checkin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
