"""initial migration

Revision ID: 6d1a734a6023
Revises: 
Create Date: 2024-07-17 10:55:34.263685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1a734a6023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefecture_name', sa.String(), nullable=False),
    sa.Column('capital_city', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('prefecture_info', sa.String(), nullable=False),
    sa.Column('prefecture_flag', sa.String(), nullable=True),
    sa.Column('prefecture_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capital_city'),
    sa.UniqueConstraint('prefecture_name')
    )
    op.create_table('regsitered_business_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_info', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('home_country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_admins_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('building_numbers', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('neighbourhood', sa.String(), nullable=False),
    sa.Column('date_registered', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('card_info', sa.String(), server_default='', nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_businesses_id_users')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_businesses_prefecture_id_prefectures')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('home_country', sa.String(), nullable=True),
    sa.Column('current_town', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_citizens_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('home_country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_travelers_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_rating', sa.Integer(), nullable=False),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_business_reviews_admin_id_admins')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_reviews_business_id_businesses')),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_business_reviews_citizen_id_citizens')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_business_reviews_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('business_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_types_business_id_businesses')),
    sa.ForeignKeyConstraint(['business_type_id'], ['regsitered_business_types.id'], name=op.f('fk_business_types_business_type_id_regsitered_business_types')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefecture_review_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_prefecture_review_types_admin_id_admins')),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], name=op.f('fk_prefecture_review_types_citizen_id_citizens')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_prefecture_review_types_prefecture_id_prefectures')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_prefecture_review_types_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefecture_review_types')
    op.drop_table('business_types')
    op.drop_table('business_reviews')
    op.drop_table('travelers')
    op.drop_table('citizens')
    op.drop_table('businesses')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('regsitered_business_types')
    op.drop_table('prefectures')
    # ### end Alembic commands ###
