"""create business_types table

Revision ID: 72fcf39dc2e2
Revises: 02acc51586c9
Create Date: 2024-07-08 20:27:10.451176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fcf39dc2e2'
down_revision = '02acc51586c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('business_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_types_business_id_businesses')),
    sa.ForeignKeyConstraint(['business_type_id'], ['regsitered_business_types.id'], name=op.f('fk_business_types_business_type_id_regsitered_business_types')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_types')
    # ### end Alembic commands ###
