"""changed table name of businesses

Revision ID: 793e00e2e579
Revises: d57d6fac0030
Create Date: 2024-07-05 23:32:02.454546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793e00e2e579'
down_revision = 'd57d6fac0030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('building_numbers', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('neighbourhood', sa.String(), nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_businesses_id_users')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_businesses_prefecture_id_prefectures')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('buisnesses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buisnesses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('opening_time', sa.TIME(), nullable=False),
    sa.Column('closing_time', sa.TIME(), nullable=False),
    sa.Column('postal_code', sa.VARCHAR(), nullable=False),
    sa.Column('building_numbers', sa.VARCHAR(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('neighbourhood', sa.VARCHAR(), nullable=False),
    sa.Column('prefecture_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='fk_buisnesses_id_users'),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name='fk_buisnesses_prefecture_id_prefectures'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('businesses')
    # ### end Alembic commands ###
