"""create localBusinessSites table

Revision ID: 8e59722ce976
Revises: f0af7d24f9c5
Create Date: 2024-07-05 15:05:04.950856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e59722ce976'
down_revision = 'f0af7d24f9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buisnesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_number', sa.Integer(), nullable=True),
    sa.Column('address_line_one', sa.String(), nullable=False),
    sa.Column('address_line_two', sa.String(), nullable=True),
    sa.Column('address_line_three', sa.String(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_buisnesses_id_users')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_buisnesses_prefecture_id_prefectures')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buisnesses')
    # ### end Alembic commands ###
