"""updating business pictures table

Revision ID: 9b7ad420d9de
Revises: a2bfc3623592
Create Date: 2024-08-07 13:04:20.081407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7ad420d9de'
down_revision = 'a2bfc3623592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_photos', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
