"""update business reviews tables so that it is either a traveler or citizens review

Revision ID: a10012acf89f
Revises: 1b627565522b
Create Date: 2024-07-07 23:43:25.141601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10012acf89f'
down_revision = '1b627565522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reviews', schema=None) as batch_op:
        batch_op.alter_column('traveler_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('citizen_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_reviews', schema=None) as batch_op:
        batch_op.alter_column('citizen_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('traveler_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
