"""creating prefecture photos table

Revision ID: a2bfc3623592
Revises: 91d38297263b
Create Date: 2024-08-04 17:20:18.817311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bfc3623592'
down_revision = '91d38297263b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefecture_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_route', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prefecture_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_prefecture_photos_business_id_businesses')),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_prefecture_photos_prefecture_id_prefectures')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prefecture_photos_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefecture_photos')
    # ### end Alembic commands ###
