"""update business class to show card info

Revision ID: a6cbd58e08a7
Revises: aa5a39d1a339
Create Date: 2024-07-16 20:02:49.556677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cbd58e08a7'
down_revision = 'aa5a39d1a339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_info', sa.String(), server_default='Please enter a small introduction', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('card_info')

    # ### end Alembic commands ###
