"""update business wishlist table

Revision ID: b175cd8c4b90
Revises: 6084c8a59d17
Create Date: 2024-08-12 12:19:04.282519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b175cd8c4b90'
down_revision = '6084c8a59d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_wishlist', schema=None) as batch_op:
        batch_op.drop_column('wishlist_date')

    # ### end Alembic commands ###
