"""update prefecture category reviews table

Revision ID: c342fe780bcd
Revises: f5291b40df2a
Create Date: 2024-08-18 20:49:22.187674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c342fe780bcd'
down_revision = 'f5291b40df2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_prefecture_reviews_citizen_id_citizens', type_='foreignkey')
        batch_op.drop_constraint('fk_prefecture_reviews_admin_id_admins', type_='foreignkey')
        batch_op.drop_constraint('fk_prefecture_reviews_traveler_id_travelers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_prefecture_reviews_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('traveler_id')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('citizen_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefecture_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citizen_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('traveler_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_prefecture_reviews_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_prefecture_reviews_traveler_id_travelers', 'travelers', ['traveler_id'], ['id'])
        batch_op.create_foreign_key('fk_prefecture_reviews_admin_id_admins', 'admins', ['admin_id'], ['id'])
        batch_op.create_foreign_key('fk_prefecture_reviews_citizen_id_citizens', 'citizens', ['citizen_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
