"""update localBusinessSites table

Revision ID: cf09ba213efc
Revises: 8e59722ce976
Create Date: 2024-07-05 15:10:08.153124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf09ba213efc'
down_revision = '8e59722ce976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buisnesses', schema=None) as batch_op:
        batch_op.alter_column('address_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buisnesses', schema=None) as batch_op:
        batch_op.alter_column('address_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
