"""update LocalBusinessSites with correct addresses

Revision ID: d57d6fac0030
Revises: cf09ba213efc
Create Date: 2024-07-05 15:21:03.766083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57d6fac0030'
down_revision = 'cf09ba213efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buisnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('building_numbers', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('neighbourhood', sa.String(), nullable=False))
        batch_op.drop_column('address_line_two')
        batch_op.drop_column('address_line_one')
        batch_op.drop_column('address_number')
        batch_op.drop_column('address_line_three')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buisnesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_three', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('address_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('address_line_one', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('address_line_two', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('neighbourhood')
        batch_op.drop_column('city')
        batch_op.drop_column('building_numbers')
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
