"""add business wishlist column to business wishlist table

Revision ID: f5291b40df2a
Revises: b175cd8c4b90
Create Date: 2024-08-12 12:20:20.969177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5291b40df2a'
down_revision = 'b175cd8c4b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_wishlist', schema=None) as batch_op:
        batch_op.drop_column('wishlist_date')

    # ### end Alembic commands ###
