"""create prefecture table

Revision ID: f9e1ddf9938b
Revises: 35aa3c75d2cf
Create Date: 2024-07-04 15:18:31.388473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e1ddf9938b'
down_revision = '35aa3c75d2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefecture_name', sa.String(), nullable=False),
    sa.Column('capital_city', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('prefecture_info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capital_city'),
    sa.UniqueConstraint('prefecture_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefectures')
    # ### end Alembic commands ###
