"""update Prefecture model

Revision ID: fb46aa0ebf38
Revises: f9e1ddf9938b
Create Date: 2024-07-04 16:36:00.000017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb46aa0ebf38'
down_revision = 'f9e1ddf9938b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefecture_flag', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prefecture_img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefectures', schema=None) as batch_op:
        batch_op.drop_column('prefecture_img')
        batch_op.drop_column('prefecture_flag')

    # ### end Alembic commands ###
